trigger:
- main  # Define the branch that will trigger the pipeline.

variables:
  azureSubscription: 'Your-Azure-Connection'  # Service connection name
  appName: 'YourAppName'  # Your Azure Web App name
  resourceGroup: 'YourResourceGroup'  # The resource group containing the app service
  stagingSlot: 'staging'  # The name of the staging slot
  productionSlot: 'production'  # The name of the production slot
  healthCheckUrl: 'https://yourappname-staging.azurewebsites.net/health'  # URL for the health check (adjust as needed)

stages:
- stage: DeployToStaging
  jobs:
  - job: Deploy
    displayName: 'Deploy to Staging Slot'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        package: '$(System.DefaultWorkingDirectory)/_your-repo-path/drop/*.zip'  # Path to your packaged app
        slotName: $(stagingSlot)
        resourceGroupName: $(resourceGroup)
        deploymentMethod: 'auto'  # You can use 'auto' or 'zipDeploy'

- stage: HealthCheckAndSwap
  dependsOn: DeployToStaging
  jobs:
  - job: HealthCheck
    displayName: 'Run Health Check and Swap to Production'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Running health check for staging slot"
        curl --silent --fail $(healthCheckUrl) || exit 1
      displayName: 'Run Health Check'
      
  - job: SwapToProduction
    dependsOn: HealthCheck
    condition: succeeded('HealthCheck')
    displayName: 'Swap Staging Slot to Production'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppSlotSwap@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        resourceGroupName: $(resourceGroup)
        sourceSlot: $(stagingSlot)
        targetSlot: $(productionSlot)
        action: 'swap'

